# -*- coding: utf-8 -*-
"""embedding_pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eulqr7-A6hqEx7QcORkKHcvN-2BrcwT9
"""

"""
Embedding pipeline module.

Handles:
- loading embedding model
- creating FAISS vectorstore
- saving vector database
"""
import logging

from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

def load_embedding_model():
    """Load embedding model."""

    logging.info("Loading embedding model...")

    return HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

def build_vectorstore(documents):

    print("Loading embedding model (gratis)...")

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    vectorstore = FAISS.from_documents(documents, embeddings)

    vectorstore.save_local("vectorstore_reformasi_2045")

    print("Vectorstore berhasil disimpan.")

    return vectorstore