# -*- coding: utf-8 -*-
"""pdf_parser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbyfkmJ4tpJs5iq4QE9GO4pQVyiEKjfo
"""

import os
import re
import logging
import pandas as pd
import pdfplumber
from PyPDF2 import PdfReader

def extract_pdf_text(file_path: str) -> str:

    if not os.path.exists(file_path):
        logging.error("File not found: %s", file_path)
        return ""

    text = ""

    # extract text using pdfplumber
    try:
        with pdfplumber.open(file_path) as pdf:
            for page in pdf.pages:
                text += page.extract_text() or ""

        if text.strip():
            logging.info("Text extracted using pdfplumber: %s", file_path)
            return text

    except Exception as e:
        logging.warning("pdfplumber failed for %s: %s", file_path, e)

    # Fallback using PyPDF2
    try:
        reader = PdfReader(file_path)
        for page in reader.pages:
            text += page.extract_text() or ""

        if text.strip():
            logging.info("Text extracted using PyPDF2: %s", file_path)
            return text

    except Exception as e:
        logging.warning("PyPDF2 extraction failed for %s: %s", file_path, e)

    logging.error("Text extraction failed: %s", file_path)
    return ""

# TEXT CLEANING FUNCTION
def clean_text(text: str) -> str:
    if not text:
        return ""

    # remove page numbers
    text = re.sub(r'\n\d+\n', '\n', text)

    # remove non-ASCII or unusual characters
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)

    # normalize whitespace
    text = re.sub(r'\s+', ' ', text)

    return text.strip()


# Process CSV file containing text data

def process_csv(file_path: str):

    df = pd.read_csv(file_path)

    print("Available columns:", df.columns.tolist())

    if "text" not in df.columns:
        raise ValueError("Column 'text' not found.")

    df = df[["text"]].dropna().drop_duplicates()

    print(f"Number of articles after cleaning: {len(df)}")

    combined_text = " ".join(df["text"].astype(str).tolist())

    return clean_text(combined_text)