# -*- coding: utf-8 -*-
"""vectorstore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwSfHZ42NEDWzWFyLE2uoX2bu9yQIy9n
"""

"""
Vectorstore management module.

Handles:
- creating FAISS vectorstore
- saving vectorstore
- loading vectorstore
"""

import logging
from langchain_community.vectorstores import FAISS

#Create FAISS vectorstore from document chunks
def create_vectorstore(documents, embeddings):

    logging.info("Creating FAISS vectorstore...")

    vectorstore = FAISS.from_documents(documents, embeddings)

    logging.info("Vectorstore created with %s documents", len(documents))

    return vectorstore


#Save FAISS vectorstore locally
def save_vectorstore(vectorstore, path):

    vectorstore.save_local(path)

    logging.info("Vectorstore saved at %s", path)


#Load FAISS vectorstore from disk
def load_vectorstore(path, embeddings):

    logging.info("Loading vectorstore from %s", path)

    vectorstore = FAISS.load_local(
        path,
        embeddings,
        allow_dangerous_deserialization=True
    )

    return vectorstore

#Create retriever for similarity search
def get_retriever(vectorstore, k=5):

    logging.info("Retriever created with top %s results", k)

    return vectorstore.as_retriever(
      search_kwargs={"k": k}
    )